import java.util.Arrays;
import java.util.List;
import java.util.stream.*;
import java.util.function.*;
import java.util.*;
import java.util.Random;
public class PSPWeek9 {
public static void main(String[] args) {
List<Integer> ints = Arrays.asList(5, 3, 25, 7, 63, 4, 73, 42, 72, 3, 64, 6, 0, -34, 2, -521, 32);
List<String> strings = Arrays.asList("HELLO", "aPpLe", "WORLD", "carrot", "JAVA", "cow", "fig",
"PROGRAMMING");
List<Double> doubles = List.of(32.1, 2.76, 3.0, 1.45, 89.2);
List<String> namesList = List.of("Mary", "Jane");
List<Integer> ints2 = Arrays.asList(5, -3, 15, 7, 3);
/*
* 1. Use a Predicate to filter a list of integers, keeping only those that are
* divisible by 3.
*/
Predicate<Integer> divBy3 = (number) -> number%3==0;// YOUR CODE - function that can be applied
List<Integer> integers =  ints.stream().filter(divBy3).collect(Collectors.toList());
System.out.println("Input:" + ints);
System.out.println("output:" + integers);
System.out.println();
/*
* 2. Create a Function that takes a double and returns the whole number
* portion.
*/
Function<Double, Integer> intPart = doubleNum -> (int) (double) doubleNum; 
List<Integer> wholeParts = doubles.stream().map(intPart).collect(Collectors.toList());
System.out.println("Input:" + doubles);
System.out.println("Output: " + wholeParts);
System.out.println();
/* 3. Use a Consumer to print each string in a list in lowercase. */
//Your code
List<String> lowerStrings = strings.stream()
                                    .map(String::toLowerCase)
                                    .collect(Collectors.toList());
System.out.println("Input:" + strings);
System.out.println("Output: " + lowerStrings);
System.out.println();
/*
* 4. Write code that filters a list of integers to keep only those greater than
* 50 and divisible by 3. Combine multiple predicates and resuse your predicate
* from 1.
*/
System.out.println("Input:" + ints);
List<Integer> result = ints.stream().filter(e ->e<50).filter( e -> (e%3)==0).collect(Collectors.toList());
System.out.println("Output"+ result);
System.out.println();
/*
* 5. Write code to square each number in a list of integers and then calculate the
* sum of all squared values.
*/
//Your code
System.out.println("Input:" + ints2);
Double sumOfSquares = ints2.stream().mapToDouble(e-> Math.pow(e, 2)).reduce(0.0,(a,b)-> a+b);
System.out.println("Output(Sum of squares): " + sumOfSquares );
System.out.println();
/*
*6. Write a function to add a prefix "Hello, " to a given string. Apply it to a
* list of names.
*/
List<String> newStr = namesList.stream().map(e-> "Hello" + e).collect(Collectors.toList());
System.out.println("Input:" + namesList);
System.out.println("Output: "+ newStr);
System.out.println();
/*
* 7. Write a function that converts a number to its cube.
* Write a function that converts a number to a string prefixed by "Result: ".
* Chain these functions and
* apply them to a list of numbers.
*/
//Your code
System.out.println("Input:" + ints2);
Function<Integer,Integer> cubedFunction = number-> (int) Math.pow(number,3);
Function<Integer,String> strFunction = number -> "Result:"+ number.toString();
List<String> resultOf = ints2.stream().map(cubedFunction ).map(strFunction).collect(Collectors.toList());
System.out.println("Output (cubed and prefixed with Result): " + resultOf);
System.out.println();
/**
* 8. Write a Supplier to generate random integers between 1 and 100.
* Call the supplier 10 times and create a list of the the generated values.
*/
//Your code
Random random = new Random();
Supplier<Integer> tSupplier = () -> random.nextInt(100) + 1;
List<Integer> intList = Stream.generate(tSupplier).limit(10).collect(Collectors.toList());
System.out.println("List generated by Supplier: " + intList);
System.out.println();
/**
* 9. Create a BiFunction that takes two strings
* and returns their concatenation with a space in between.
* Use it on pairs of strings.
* https://docs.oracle.com/javase/8/docs/api/java/util/function/BiFunction.html
*/
List<String> strList2 = List.of("Would", "this", "darkness", "ever", "lift?");
BiFunction<String,String,String> strChanged = (e,n) -> e + " " + n;
String newString = strList2.stream()
                        .reduce((e, n) -> strChanged.apply(e, n))
                        .orElse("");
System.out.println("Input: " + strList2);
System.out.println("Output: " + newString);
System.out.println();
/**
* 10. Write a method that takes a list of strings and a Predicate<String> as
* arguments.
* The method should return a new list containing only the strings that satisfy
* the predicate. Test it with:
* (a) Strings that start with "P",
* (b) Strings longer than 4 characters.
*/
//Your code
List<String> list3 = List.of("amy", "Peter", "Pam", "Paul", "Neela", "Porter");
        System.out.println("Input List: " + list3);

        // (a) Testing strings that start with "P"
        List<String> startsWithP = filterList(list3, s -> s.startsWith("P"));
        System.out.println("Filtered (Starts with P): " + startsWithP);

        // (b) Testing strings longer than 4 characters
        List<String> longerThan4 = filterList(list3, s -> s.length() > 4);
        System.out.println("Filtered (Longer than 4): " + longerThan4);
        
        System.out.println();
}
public static List<String> filterList(List<String> input, Predicate<String> condition) {
    return input.stream()
                .filter(condition)
                .collect(Collectors.toList());
}    
}
